### ISSUE TITLE
Cube 3rd Gen

### ISSUE THREAD

**Issue by mattwilko** [fritzw/cube-utils#1]
Is there any chance of support for the cube 3rd gen printer. I believe it using the same encryption as the cube pro but the file extension is different?

**Comment by fritzw** [comment]
Maybe, if the encryption algorithm is the same. However, then we would still need the encryption *password*, which is different between CubePro and CubeX, for example. One way to get the password would be to extract it from the software which generates the .cube3 files.

**Comment by bolsoncerrado** [comment]
Apparently the encryption password is the same for the Cube3.

**Comment by Mythandar** [comment]
It is.  I've been using the cubepro encryption file to encrypt my .bfb's I'm making with kisslicer and simplify3d.  I just have to rename the file extension to .cube3 when it's done.  A minor annoyance.  Having a version that just changes the name of the outputed file from .cubepro to .cube3 would be appreciated.

Your cubepro decryption program also works with the cube3 files made by the cubeprint software.  There's one catch tho, cube print inserts a thumbnail of the print into the .cube3 file which messes up the decryption.  I had to catch the .cube3 file it makes before the thumbnail gets inserted into it.  Once i did that it decrypted fine using the cubepro decryptor.

**Comment by bolsoncerrado** [comment]
So did anyone come up to the best Simplify3D profile to export to .bfb optimized for a cube3?

**Comment by luizrenault** [comment]
How do you get the .cube3 file before the thumbnail is inserted?

**Comment by Mythandar** [comment]
I've made a program for windows that helps make it easier to get the .cube3 before the thumbnail is inserted.  Here's a link to the forum post for it.  http://www.print3dforum.com/showthread.php/1002-Cube-Print-Temperature-Modifier-*beta*  

That program I actually made so you can use the cubeprint software with filaments that need a different temperature than what the cube3 defaults to, it uses 215c for pla and 260c for abs.  If you just want to get the .bfb out of it then just go through the first 3 steps, the .bfb will be in your save directory.

Hope this helps.
